// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0IOgYrE887k6LyzBESG-lMxP_jj4cFY',
    appId: '1:887179659419:web:361b3ef9e99e28ac791e3e',
    messagingSenderId: '887179659419',
    projectId: 'dineflow-5dac1',
    authDomain: 'dineflow-5dac1.firebaseapp.com',
    storageBucket: 'dineflow-5dac1.firebasestorage.app',
    measurementId: 'G-00RXFYXSP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAW6sqoduiwOUGo_vfLTIPP_OPSPkxABo',
    appId: '1:887179659419:android:9e8388a526b8996c791e3e',
    messagingSenderId: '887179659419',
    projectId: 'dineflow-5dac1',
    storageBucket: 'dineflow-5dac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYioD3lrXmfVub3MQOl-dEaQQtTkYjurk',
    appId: '1:887179659419:ios:748641cc6dfb3201791e3e',
    messagingSenderId: '887179659419',
    projectId: 'dineflow-5dac1',
    storageBucket: 'dineflow-5dac1.firebasestorage.app',
    iosBundleId: 'com.example.dineflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYioD3lrXmfVub3MQOl-dEaQQtTkYjurk',
    appId: '1:887179659419:ios:748641cc6dfb3201791e3e',
    messagingSenderId: '887179659419',
    projectId: 'dineflow-5dac1',
    storageBucket: 'dineflow-5dac1.firebasestorage.app',
    iosBundleId: 'com.example.dineflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm0IOgYrE887k6LyzBESG-lMxP_jj4cFY',
    appId: '1:887179659419:web:8ccb000e69c8c13d791e3e',
    messagingSenderId: '887179659419',
    projectId: 'dineflow-5dac1',
    authDomain: 'dineflow-5dac1.firebaseapp.com',
    storageBucket: 'dineflow-5dac1.firebasestorage.app',
    measurementId: 'G-9E5JFS0R9P',
  );
}
